// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK_wZT-uYNIAXhGulFXqo-q0zJhP4Xe0Y',
    appId: '1:210423840068:web:bc81e8c49be49bb8b96b11',
    messagingSenderId: '210423840068',
    projectId: 'sheroproject',
    authDomain: 'sheroproject.firebaseapp.com',
    storageBucket: 'sheroproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYZx6xCsaVoyDBzpKviXpEG-IWMtwT6mk',
    appId: '1:210423840068:android:e37a0c2b01813579b96b11',
    messagingSenderId: '210423840068',
    projectId: 'sheroproject',
    storageBucket: 'sheroproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7l1NgXqamAwOy49TJyWHi8BhdVxh2KO8',
    appId: '1:210423840068:ios:7c957f0700477595b96b11',
    messagingSenderId: '210423840068',
    projectId: 'sheroproject',
    storageBucket: 'sheroproject.appspot.com',
    iosClientId: '210423840068-oij4mpnc16d8did3in3s40pj2pdiqe2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myShero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7l1NgXqamAwOy49TJyWHi8BhdVxh2KO8',
    appId: '1:210423840068:ios:c6bec6e8f51ec41fb96b11',
    messagingSenderId: '210423840068',
    projectId: 'sheroproject',
    storageBucket: 'sheroproject.appspot.com',
    iosClientId: '210423840068-m7q5eup11tas2nbhaijpo4k31mbmjf3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myShero.RunnerTests',
  );
}
